manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: Preacher325
      url-base: https://github.com/Preacher325
  projects:
    - name: zmk
      remote: Preacher325
      revision: Dual
      import: app/west.yml
  self:
    path: config
